databases:
  - name: eatnow2_db
    databaseName: eatnow2
    user: root

services:
  - type: web
    name: Eatnow
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn deployment.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eatnow2
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4