# Generated by Django 5.0.1 on 2024-02-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
