# Generated by Django 5.0.1 on 2024-01-31 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_cart_cartitem_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
