# Generated by Django 5.0.1 on 2024-02-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_menuitemordermodel_ordermodel_menu_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='menu_items',
        ),
        migrations.DeleteModel(
            name='MenuItemOrderModel',
        ),
    ]
