# Generated by Django 5.0.1 on 2024-02-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_delete_profile'),
        ('customer', '0006_profile'),
    ]

    operations = [
    ]
