# Generated by Django 5.0.1 on 2024-01-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_ordermodel_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('products', models.ManyToManyField(to='customer.menuitem')),
            ],
        ),
    ]
