# Generated by Django 5.0.1 on 2024-01-30 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_cuisinetype_remove_restaurantname_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantname',
            name='type',
        ),
        migrations.AddField(
            model_name='restaurantname',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.cuisinetype'),
            preserve_default=False,
        ),
    ]
