<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-02-07 20:45
=======
# Generated by Django 5.0.1 on 2024-02-07 19:40
>>>>>>> ad77dcff595c58e4173634ac25b195c7ddbe62ca

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='menu_images/'),
        ),
    ]
