# Generated by Django 5.0.1 on 2024-01-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_remove_restaurantname_type_restaurantname_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantname',
            name='image',
            field=models.ImageField(blank=True, upload_to='restaurant_images/'),
        ),
    ]
